# Generated by Django 5.0.7 on 2024-08-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionar_usuarios', '0002_alter_usuario_groups_alter_usuario_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
