# Generated by Django 5.1 on 2024-08-18 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionar_categoria', '0001_initial'),
        ('gestionar_marca', '0001_initial'),
        ('gestionar_presentacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.FloatField()),
                ('unidad_de_medida', models.CharField(choices=[('KG', 'Kilogramo'), ('HG', 'Hectogramo'), ('G', 'Gramo'), ('DAG', 'Decagramo'), ('DG', 'Decigramo'), ('CG', 'Centigramo'), ('MG', 'Miligramo'), ('KL', 'Kilolitro'), ('HL', 'Hectolitro'), ('DAL', 'Decalitro'), ('L', 'Litro'), ('DL', 'Decilitro'), ('CL', 'Centilitro'), ('ML', 'Mililitro')], max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionar_categoria.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionar_marca.marca')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionar_presentacion.presentacion')),
            ],
        ),
    ]
