# Generated by Django 5.1 on 2024-08-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio_venta', models.FloatField()),
                ('precio_compra', models.FloatField()),
                ('cantidad_Stock', models.IntegerField()),
                ('unidades_Paquete', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
