# Generated by Django 5.1 on 2024-08-18 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionar_productos', '0001_initial'),
        ('gestionar_proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_Compra', models.DateTimeField()),
                ('total_Compra', models.FloatField()),
                ('cantidad_Producto', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('proveedor_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionar_proveedor.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Compra_has_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionar_compra.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionar_productos.producto')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='productos',
            field=models.ManyToManyField(through='gestionar_compra.Compra_has_producto', to='gestionar_productos.producto'),
        ),
    ]
