# Generated by Django 4.0 on 2024-08-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionar_productos', '0001_initial'),
        ('gestionar_compra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='productos',
            field=models.ManyToManyField(through='gestionar_compra.Compra_has_producto', to='gestionar_productos.Producto'),
        ),
    ]
